
version: '3'

services:
  dashboard:
    build: .
    ports:
      - "8080:8080"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

